#!/usr/bin/env python3
"""
Rename auto-generated filenames for images, documents, media, and application files
using OpenAI.
"""

import argparse
import time
import base64
import json
import mimetypes
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Callable, Optional, Tuple
import hashlib
import csv

try:
    from openai import OpenAI
except ImportError:
    import openai

    OpenAI = openai.OpenAI

MISSING_PYMUPDF_WARNED = False
StatusReporter = Optional[Callable[[str], None]]


def emit_status(reporter: StatusReporter, message: str) -> None:
    if reporter:
        reporter(message)


def format_bytes(num_bytes: int) -> str:
    value = float(num_bytes)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            if unit == "B":
                return f"{int(value)} {unit}"
            return f"{value:.1f} {unit}"
        value /= 1024


def check_dependencies() -> None:
    if not shutil.which("ffmpeg"):
        raise SystemExit("ffmpeg is not installed. Install it with: brew install ffmpeg")

    try:
        import fitz  # PyMuPDF
    except Exception:
        raise SystemExit(
            "PyMuPDF is not installed. Install it with: "
            "pip install -r \"files and folders organizer - requirements.txt\""
        )


IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif", ".eps"}
DOCUMENT_EXTS = {
    ".pdf",
    ".docx",
    ".txt",
    ".rtf",
    ".csv",
    ".pptx",
    ".ttf",
    ".py",
    ".html",
    ".eml",
    ".xls",
    ".psd",
    ".dn",
}
THREED_EXTS = {
    ".scad",
    ".stl",
    ".gcode",
}
MEDIA_EXTS = {
    ".mp4",
    ".mov",
    ".mp3",
    ".wav",
    ".m4a",
    ".aup3",
    ".svg",
    ".ico",
    ".icl",
    ".ics",
}
APPLICATION_EXTS = {".app", ".dmg", ".pkg", ".exe", ".zip", ".webp", ".xml", ".iso"}

SUPPORTED_EXTS = IMAGE_EXTS | DOCUMENT_EXTS | THREED_EXTS | MEDIA_EXTS | APPLICATION_EXTS

AUTOGEN_PATTERNS = [
    r"^img_\d+$",
    r"^img\d+$",
    r"^dsc_?\d+$",
    r"^dscn\d+$",
    r"^pxl_\d+$",
    r"^vid_\d+$",
    r"^img-\d+$",
    r"^\d{8}_\d{6}$",
    r"^screenshot( |-|_)\d{4}[-_]\d{2}[-_]\d{2}.*$",
    r"^screen shot \d{4}-\d{2}-\d{2} at .*",
    r"^whatsapp image \d{4}-\d{2}-\d{2} at .*",
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    r"^[0-9a-f]{12,}$",
]

CATEGORY_TEMPLATES = {
    "document": "document - {desc}",
    "screenshot": "screenshot of {desc}",
    "photo": "photo of reality - {desc}",
    "schematic": "schematic of {desc}",
    "cartoon": "cartoon of {desc}",
    "3d": "3d model file {desc}",
    "media": "media video file {desc}",
    "application": "application file {desc}",
}

CATEGORY_PREFIXES = {
    "document": "document - ",
    "screenshot": "screenshot of ",
    "photo": "photo of reality - ",
    "schematic": "schematic of ",
    "cartoon": "cartoon of ",
    "3d": "3d model file ",
    "media": "media video file ",
    "application": "application file ",
}

DEFAULT_DESTS = {
    "document": Path.home() / "Documents",
    "screenshot": Path.home() / "Pictures" / "Screenshots",
    "photo": Path.home() / "Pictures" / "Photos",
    "schematic": Path.home() / "Pictures" / "Schematics",
    "cartoon": Path.home() / "Pictures" / "Cartoons",
    "3d": Path.home() / "Documents" / "3D",
    "media": Path.home() / "Movies",
    "application": Path.home() / "Applications",
}

BRANDS_FILE = Path(__file__).resolve().parent / "brands.txt"
BRAND_OVERRIDES_FILE = Path(__file__).resolve().parent / "brand_overrides.csv"


def is_autogenerated(stem: str) -> bool:
    s = stem.strip().lower()
    if not s:
        return True
    for pat in AUTOGEN_PATTERNS:
        if re.fullmatch(pat, s):
            return True

    # Mostly digits/symbols, no spaces, short-ish
    if " " not in s:
        digits = sum(ch.isdigit() for ch in s)
        letters = sum(ch.isalpha() for ch in s)
        if digits >= max(6, int(0.6 * len(s))) and letters <= 2:
            return True

    # Long hex-looking strings
    if re.fullmatch(r"[0-9a-f]{16,}", s):
        return True

    return False


def is_human_readable(stem: str) -> bool:
    s = stem.strip()
    if not s:
        return False
    if is_autogenerated(s):
        return False

    tokens = [t for t in re.split(r"[ _\-]+", s) if t]
    word_tokens = [t for t in tokens if re.search(r"[A-Za-z]", t)]
    if len(word_tokens) >= 2:
        return True

    # Any alphabetic with spaces or longer length
    if re.search(r"[A-Za-z]", s) and (" " in s or len(s) >= 14):
        return True

    return False


def is_mnemonically_poor(stem: str) -> bool:
    s = stem.strip()
    if not s:
        return True
    if "could_not_classify" in s.lower():
        return False
    lower = s.lower()
    if re.search(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", lower):
        return True
    digits = sum(ch.isdigit() for ch in s)
    letters = sum(ch.isalpha() for ch in s)
    seps = sum(ch in "-_." for ch in s)
    if len(s) >= 32 and " " not in s:
        return True
    if digits >= max(6, int(0.4 * len(s))) and letters <= int(0.4 * len(s)):
        return True
    if seps >= 4 and digits >= 6:
        return True
    return False


def sanitize_filename(name: str) -> str:
    # Replace characters that are risky across filesystems
    cleaned = re.sub(r"[\\/:*?\"<>|]", "-", name)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def ensure_unique_path(path: Path) -> Path:
    if not path.exists():
        return path
    base = path.stem
    ext = path.suffix
    parent = path.parent
    i = 2
    while True:
        candidate = parent / f"{base} - {i}{ext}"
        if not candidate.exists():
            return candidate
        i += 1


def extract_date_from_stem(stem: str) -> str:
    s = stem.lower()
    # Match YYYY-MM-DD or YYYY_MM_DD
    m = re.search(r"(20\d{2})[-_](\d{2})[-_](\d{2})", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"

    # Match YYYYMMDD
    m = re.search(r"(20\d{2})(\d{2})(\d{2})", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"

    return ""


def parse_date_from_text(text: str) -> str:
    if not text:
        return ""
    # Prefer explicit YYYY-MM-DD or YYYY/MM/DD
    m = re.search(r"(20\d{2})[-/](\d{2})[-/](\d{2})", text)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"

    # Handle DD/MM/YYYY or MM/DD/YYYY
    m = re.search(r"(\d{1,2})[-/](\d{1,2})[-/](20\d{2})", text)
    if m:
        a = int(m.group(1))
        b = int(m.group(2))
        y = m.group(3)
        # Disambiguate: if a > 12, it's DD/MM; if b > 12, it's MM/DD; else assume MM/DD (US)
        if a > 12:
            d, mo = a, b
        elif b > 12:
            mo, d = a, b
        else:
            mo, d = a, b
        return f"{y}-{mo:02d}-{d:02d}"

    return ""


def year_month_from_date(date_str: str) -> tuple[str, str]:
    if not date_str:
        return "Unknown", "Unknown"
    m = re.match(r"(20\d{2})-(\d{2})-(\d{2})", date_str)
    if not m:
        return "Unknown", "Unknown"
    return m.group(1), m.group(2)


def progress_bar(scanned: int, total: int, width: int = 50) -> str:
    if total <= 0:
        return "[" + ("?" * width) + "]"
    bar = ["-"] * width
    pct_text = f"{(scanned / total) * 100:0.1f}%"
    idx = int((scanned / total) * max(1, width - len(pct_text)))
    idx = max(0, min(width - len(pct_text), idx))
    for i, ch in enumerate(pct_text):
        bar[idx + i] = ch
    return "[" + "".join(bar) + "]"


def format_eta(seconds: float) -> str:
    seconds = max(0, int(seconds))
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    if h > 0:
        return f"{h:d}h{m:02d}m{s:02d}s"
    return f"{m:02d}m{s:02d}s"


def format_clock(timestamp: Optional[float] = None) -> str:
    if timestamp is None:
        timestamp = time.time()
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(timestamp))


def print_phase_progress(
    label: str,
    current: int,
    total: int,
    started: float,
    current_label: str = "scanned",
    **metrics: object,
) -> None:
    elapsed = max(1.0, time.time() - started)
    rate = current / elapsed if current > 0 else 0.0
    remaining = max(0, total - current)
    eta = format_eta(remaining / rate) if rate > 0 else "??m??s"
    bar = progress_bar(current, total)
    fields = [
        f"{current_label}={current}",
        *(f"{key}={value}" for key, value in metrics.items()),
        f"remaining={remaining}",
        f"rate={rate:.2f} files/sec",
        f"eta={eta}",
    ]
    print(
        f"\n\n{label} {bar} clock={format_clock()} elapsed={format_eta(elapsed)} "
        + " ".join(fields)
        + "\n\n"
    )


def image_to_data_url(path: Path) -> Optional[str]:
    if path.suffix.lower() == ".eps":
        tmp_dir = Path(tempfile.mkdtemp(prefix="rename_eps_"))
        png_path = tmp_dir / "preview.png"
        try:
            subprocess.run(
                ["sips", "-s", "format", "png", str(path), "--out", str(png_path)],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            if png_path.exists():
                return bytes_to_data_url(png_path.read_bytes(), "image/png")
        except Exception:
            return None
        finally:
            shutil.rmtree(tmp_dir, ignore_errors=True)

    mime, _ = mimetypes.guess_type(path.name)
    if not mime:
        if path.suffix.lower() in {".jpg", ".jpeg"}:
            mime = "image/jpeg"
        elif path.suffix.lower() == ".png":
            mime = "image/png"
        elif path.suffix.lower() == ".webp":
            mime = "image/webp"
        elif path.suffix.lower() == ".gif":
            mime = "image/gif"
        elif path.suffix.lower() == ".avif":
            mime = "image/avif"
        else:
            return None

    data = path.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def bytes_to_data_url(data: bytes, mime: str) -> str:
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def load_brand_map() -> list[tuple[str, list[str]]]:
    if not BRANDS_FILE.exists():
        return []
    entries: list[tuple[str, list[str]]] = []
    for line in BRANDS_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|") if p.strip()]
        if not parts:
            continue
        canonical = parts[0]
        aliases = parts
        entries.append((canonical, aliases))
    return entries


def load_brand_overrides() -> dict[str, str]:
    if not BRAND_OVERRIDES_FILE.exists():
        return {}
    overrides: dict[str, str] = {}
    with BRAND_OVERRIDES_FILE.open(newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        for row in reader:
            if not row or row[0].startswith("#"):
                continue
            if len(row) >= 2:
                overrides[row[0].strip()] = row[1].strip()
    return overrides


def classify_image(
    client: OpenAI,
    model: str,
    detail: str,
    data_url: str,
    reporter: StatusReporter = None,
    label: str = "image",
) -> dict:
    if not data_url:
        return {"category": "could_not_classify", "description": ""}

    schema = {
        "type": "object",
        "properties": {
            "category": {
                "type": "string",
                "enum": [
                    "document",
                    "screenshot",
                "photo",
                "schematic",
                "cartoon",
                "media",
                "application",
                "could_not_classify",
            ],
        },
            "description": {"type": "string"},
        },
        "required": ["category", "description"],
        "additionalProperties": False,
    }

    prompt = (
        "Classify the image into one of the categories: document, screenshot, "
        "photo, schematic, cartoon, media, application, could_not_classify. "
        "If you choose document/screenshot/photo/schematic/cartoon, provide a short "
        "description (3-10 words) that will be used in a filename. "
        "If you choose media, describe what the media is (3-10 words). "
        "If you choose application, describe the app or installer (3-10 words). "
        "If the image is a document and you can recognize the type, use that (e.g., bank statement). "
        "If you choose could_not_classify, set description to an empty string."
    )

    emit_status(reporter, f"OpenAI image classification started for {label}")
    started = time.time()
    try:
        response = client.responses.create(
            model=model,
            input=[
                {
                    "role": "user",
                    "content": [
                        {"type": "input_text", "text": prompt},
                        {"type": "input_image", "image_url": data_url, "detail": detail},
                    ],
                }
            ],
            text={
                "format": {
                    "type": "json_schema",
                    "name": "image_label",
                    "schema": schema,
                    "strict": True,
                }
            },
        )
    except Exception as exc:
        # If the file isn't a valid image (corrupt or mislabeled), skip gracefully.
        if "invalid image" in str(exc).lower() or "invalid_request_error" in str(exc).lower():
            emit_status(reporter, f"OpenAI image classification skipped invalid image for {label}")
            return {"category": "could_not_classify", "description": ""}
        raise
    emit_status(reporter, f"OpenAI image classification finished for {label} in {time.time() - started:.1f}s")

    raw = response.output_text
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"category": "could_not_classify", "description": ""}


def classify_text_document(
    client: OpenAI,
    model: str,
    text: str,
    reporter: StatusReporter = None,
    label: str = "document",
) -> dict:
    schema = {
        "type": "object",
        "properties": {
            "category": {"type": "string", "enum": ["document", "could_not_classify"]},
            "description": {"type": "string"},
        },
        "required": ["category", "description"],
        "additionalProperties": False,
    }

    prompt = (
        "You will be given extracted text from a document. "
        "Classify it as document or could_not_classify. "
        "If document, provide a short description (3-10 words) for a filename. "
        "If could_not_classify, set description to an empty string."
    )

    emit_status(reporter, f"OpenAI text classification started for {label}")
    started = time.time()
    response = client.responses.create(
        model=model,
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_text", "text": prompt},
                    {"type": "input_text", "text": text},
                ],
            }
        ],
        text={
            "format": {
                "type": "json_schema",
                "name": "doc_label",
                "schema": schema,
                "strict": True,
            }
        },
    )

    emit_status(reporter, f"OpenAI text classification finished for {label} in {time.time() - started:.1f}s")
    raw = response.output_text
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"category": "could_not_classify", "description": ""}


def classify_pdf_document(
    client: OpenAI,
    model: str,
    detail: str,
    data_url: Optional[str],
    text: str,
    reporter: StatusReporter = None,
    label: str = "pdf",
) -> dict:
    schema = {
        "type": "object",
        "properties": {
            "doc_type": {
                "type": "string",
                "enum": ["bill", "statement", "report", "image", "other", "could_not_classify"],
            },
            "brand": {"type": "string"},
            "subject": {"type": "string"},
            "date": {"type": "string"},
        },
        "required": ["doc_type", "brand", "subject", "date"],
        "additionalProperties": False,
    }

    prompt = (
        "Classify this PDF. Use doc_type: bill, statement, report, image, other, or could_not_classify. "
        "If a recognizable brand/logo is present, set brand to its name (e.g., TELUS, BC Hydro, RBC). "
        "Provide a short subject (3-10 words) that would be useful in a filename. "
        "Extract the most relevant document date and format it as YYYY-MM-DD (empty string if unknown). "
        "If not sure, set brand to empty string. If could_not_classify, subject can be empty."
    )

    content = [{"type": "input_text", "text": prompt}]
    if text:
        content.append({"type": "input_text", "text": text[:6000]})
    if data_url:
        content.append({"type": "input_image", "image_url": data_url, "detail": detail})

    emit_status(reporter, f"OpenAI PDF classification started for {label}")
    started = time.time()
    response = client.responses.create(
        model=model,
        input=[{"role": "user", "content": content}],
        text={
            "format": {
                "type": "json_schema",
                "name": "pdf_label",
                "schema": schema,
                "strict": True,
            }
        },
    )

    emit_status(reporter, f"OpenAI PDF classification finished for {label} in {time.time() - started:.1f}s")
    raw = response.output_text
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"doc_type": "could_not_classify", "brand": "", "subject": "", "date": ""}


def extract_pdf_first_page_image(path: Path) -> Optional[Tuple[bytes, str]]:
    global MISSING_PYMUPDF_WARNED
    try:
        import fitz  # PyMuPDF
    except Exception:
        if not MISSING_PYMUPDF_WARNED:
            print("Warning: PyMuPDF not installed. PDF OCR will be skipped.", file=sys.stderr)
            MISSING_PYMUPDF_WARNED = True
        return None

    try:
        doc = fitz.open(path)
        if doc.page_count < 1:
            return None
        page = doc.load_page(0)
        pix = page.get_pixmap()
        data = pix.tobytes("png")
        return data, "image/png"
    except Exception:
        return None
    finally:
        try:
            doc.close()
        except Exception:
            pass


def extract_video_frame(path: Path) -> Optional[Path]:
    if not shutil.which("ffmpeg"):
        return None
    tmp_dir = Path(tempfile.mkdtemp(prefix="rename_media_"))
    frame_path = tmp_dir / "frame.jpg"
    cmd = [
        "ffmpeg",
        "-y",
        "-ss",
        "0",
        "-i",
        str(path),
        "-frames:v",
        "1",
        "-q:v",
        "2",
        str(frame_path),
    ]
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        return None
    if frame_path.exists():
        return frame_path
    return None


def read_text_file(path: Path, max_chars: int = 8000) -> str:
    try:
        return path.read_text(errors="ignore")[:max_chars]
    except Exception:
        return ""


def parse_category_from_stem(stem: str) -> Optional[str]:
    s = stem.lower()
    for category, prefix in CATEGORY_PREFIXES.items():
        if s.startswith(prefix):
            return category
    return None


def route_destination(path: Path) -> Optional[Path]:
    if path.name in {
        "files and folders organizer.py",
        "files and folders organizer - .env",
        "files and folders organizer - requirements.txt",
        "files and folders organizer - setup.sh",
    }:
        return None
    name = path.stem
    lower_name = name.lower()
    ext = path.suffix.lower()

    if ext in THREED_EXTS:
        if ext == ".gcode":
            if lower_name.startswith("um2"):
                return Path.home() / "Documents" / "3D" / "Ultimaker2"
            if lower_name.startswith("ce3e3v2"):
                return Path.home() / "Documents" / "3D" / "Creality Ender 3v2"
        return Path.home() / "Documents" / "3D"

    if ext == ".svg":
        return Path.home() / "Pictures"

    if ext == ".gcode":
        if lower_name.startswith("um2"):
            return Path.home() / "Documents" / "3D" / "Ultimaker2"
        if lower_name.startswith("ce3e3v2"):
            return Path.home() / "Documents" / "3D" / "Creality Ender 3v2"

    if ext == ".mp3":
        return Path.home() / "Music" / "playable" / "mp3"

    if ext == ".aup3":
        return Path.home() / "Music" / "Audacity Projects"

    if ext == ".psd":
        return Path.home() / "Pictures" / "Photoshop Projects"

    if ext == ".py":
        return Path.home() / "Documents" / "code" / "python"

    if ext == ".pdf":
        brand_map = load_brand_map()
        overrides = load_brand_overrides()
        lower_name = path.stem.lower()
        date_tag = extract_date_from_stem(path.stem)
        year, month = year_month_from_date(date_tag)

        # Manual override by filename
        override_brand = overrides.get(path.name)
        if override_brand:
            if "statement" in lower_name:
                return Path.home() / "Documents" / "Statements" / override_brand / year / month
            if "bill" in lower_name:
                return Path.home() / "Documents" / "Bills" / override_brand / year / month

        for brand, aliases in brand_map:
            if any(alias.lower() in lower_name for alias in aliases):
                if "statement" in lower_name:
                    return Path.home() / "Documents" / "Statements" / brand / year / month
                if "bill" in lower_name:
                    return Path.home() / "Documents" / "Bills" / brand / year / month

        if "unknown brand" in lower_name:
            if "statement" in lower_name:
                return Path.home() / "Documents" / "Statements" / "Unknown Brand" / year / month
            if "bill" in lower_name:
                return Path.home() / "Documents" / "Bills" / "Unknown Brand" / year / month

        if "report" in lower_name:
            # Keep reports in place if already readable
            if is_human_readable(path.stem):
                return None
            return Path.home() / "Documents" / "Reports"

        if "image-like" in lower_name or "image like" in lower_name:
            return Path.home() / "Pictures"

    category = parse_category_from_stem(path.stem)
    if not category:
        if ext in IMAGE_EXTS:
            return Path.home() / "Pictures"
        if ext in APPLICATION_EXTS:
            return Path.home() / "Applications"
        return None

    name = lower_name
    if category == "document":
        if "telus" in name:
            return Path.home() / "Documents" / "Bills" / "Telus"
        if "bank" in name:
            return Path.home() / "Documents" / "Banks"
        if "unknown brand" in name:
            if "statement" in name:
                return Path.home() / "Documents" / "Statements" / "Unknown Brand"
            if "bill" in name:
                return Path.home() / "Documents" / "Bills" / "Unknown Brand"

    return DEFAULT_DESTS.get(category)


def move_to_destination(path: Path, dest_dir: Path, skip_permission_errors: bool) -> None:
    if path.parent == dest_dir:
        return
    dest_dir.mkdir(parents=True, exist_ok=True)
    target = dest_dir / path.name
    target = ensure_unique_path(target)
    try:
        path.rename(target)
        print(f"MOVED: {path.name} -> {target}")
    except PermissionError:
        if skip_permission_errors:
            print(f"SKIP (permission): {path.name}")
        else:
            raise


def prune_empty_directories(root: Path, skip_permission_errors: bool) -> None:
    # Walk bottom-up to safely remove empty folders.
    dirs = [p for p in root.rglob("*") if p.is_dir()]
    for d in sorted(dirs, key=lambda p: len(p.parts), reverse=True):
        try:
            if not any(d.iterdir()):
                d.rmdir()
                print(f"REMOVED EMPTY DIR: {d}")
        except PermissionError:
            if skip_permission_errors:
                print(f"SKIP (permission): {d}")
            else:
                raise


def is_within(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except Exception:
        return False


def file_hash(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def dedupe_files(
    root: Path,
    recursive: bool,
    skip_permission_errors: bool,
    apply: bool,
    skip_dir: Path,
    total: int,
    started: float,
) -> tuple[int, int, int, int]:
    seen: dict[str, Path] = {}
    scanned = 0
    duplicates = 0
    deleted = 0
    permission_skips = 0
    for path in iter_files(root, recursive):
        if is_within(path, skip_dir):
            continue
        scanned += 1
        try:
            digest = file_hash(path)
        except PermissionError:
            if skip_permission_errors:
                print(f"SKIP (permission): {path}")
                permission_skips += 1
                continue
            raise

        if digest in seen:
            duplicates += 1
            if apply:
                try:
                    path.unlink()
                    print(f"DELETED DUPLICATE: {path} (kept {seen[digest]})")
                    deleted += 1
                except PermissionError:
                    if skip_permission_errors:
                        print(f"SKIP (permission): {path}")
                        permission_skips += 1
                    else:
                        raise
            else:
                print(f"DRY-RUN DUPLICATE: {path} (would delete; kept {seen[digest]})")
        else:
            seen[digest] = path
        if (scanned % 12) == 0:
            print_phase_progress(
                "Dedupe progress",
                scanned,
                total,
                started,
                duplicates=duplicates,
                deleted=deleted,
                permission_skips=permission_skips,
            )
    return scanned, duplicates, deleted, permission_skips


def build_new_name(stem: str, category: str, description: str) -> str:
    date_tag = extract_date_from_stem(stem)
    date_suffix = f" - {date_tag}" if date_tag else ""

    if category == "could_not_classify" or not description.strip():
        return f"{stem} - could_not_classify{date_suffix}"

    desc = sanitize_filename(description)
    template = CATEGORY_TEMPLATES.get(category)
    if not template:
        return f"{stem} - could_not_classify{date_suffix}"

    return template.format(desc=desc) + date_suffix


def iter_supported_paths(root: Path, recursive: bool, include_application_dirs: bool = False):
    if recursive:
        skip_dir_names = {".git", ".venv", "node_modules"}
        skip_suffixes = {".app", ".bundle", ".framework", ".pkg"}
        for dirpath, dirnames, filenames in os.walk(root, topdown=True, onerror=lambda _: None):
            # Prune directories we don't want to descend into
            pruned = []
            for d in dirnames:
                lower = d.lower()
                path = Path(dirpath) / d
                if lower in skip_dir_names:
                    continue
                if any(lower.endswith(s) for s in skip_suffixes):
                    if include_application_dirs and path.suffix.lower() in APPLICATION_EXTS:
                        yield path
                    continue
                pruned.append(d)
            dirnames[:] = pruned

            for filename in filenames:
                path = Path(dirpath) / filename
                if path.suffix.lower() in SUPPORTED_EXTS:
                    yield path
    else:
        for path in root.iterdir():
            if path.is_file() and path.suffix.lower() in SUPPORTED_EXTS:
                yield path
            elif include_application_dirs and path.is_dir() and path.suffix.lower() in APPLICATION_EXTS:
                yield path


def iter_files(root: Path, recursive: bool):
    yield from iter_supported_paths(root, recursive, include_application_dirs=False)


def get_file_kind(path: Path) -> str:
    ext = path.suffix.lower()
    if ext in IMAGE_EXTS:
        return "image"
    if ext in DOCUMENT_EXTS:
        return "document"
    if ext in THREED_EXTS:
        return "3d"
    if ext in MEDIA_EXTS:
        return "media"
    if ext in APPLICATION_EXTS:
        return "application"
    return "other"


def main():
    parser = argparse.ArgumentParser(
        description="Rename auto-generated filenames for images, documents, media, and application files."
    )
    parser.add_argument("-r", "--recursive", action="store_true", help="Recurse into subdirectories")
    parser.add_argument("--dry-run", action="store_true", help="Print actions without renaming")
    parser.add_argument("--model", default="gpt-4.1-mini", help="OpenAI model to use")
    parser.add_argument("--detail", default="high", choices=["low", "high", "auto"], help="Image detail level")
    parser.add_argument("--max", type=int, default=0, help="Max images to process (0 = no limit)")
    parser.add_argument(
        "--no-skip-permission-errors",
        action="store_true",
        help="Fail on permission errors instead of skipping",
    )
    parser.add_argument(
        "--mnemonically-boosted",
        action="store_true",
        help="Rename files with low-mnemonic filenames (e.g., UUIDs, long tokenized names)",
    )
    parser.add_argument(
        "--no-prefix-existing",
        action="store_true",
        help="Disable default behavior of prefixing supported files lacking category prefixes",
    )
    parser.add_argument(
        "--organize",
        action="store_true",
        help="Move files with recognized naming patterns into destination folders",
    )
    parser.add_argument(
        "--organize-only",
        action="store_true",
        help="Only organize files; do not rename",
    )
    parser.add_argument(
        "--prune-empty-dirs",
        action="store_true",
        help="Remove empty directories under the root (requires -r to be useful)",
    )
    parser.add_argument(
        "--dedupe",
        action="store_true",
        help="Find duplicate files by content hash (dry-run by default)",
    )
    parser.add_argument(
        "--dedupe-apply",
        action="store_true",
        help="Actually delete duplicates (implies --dedupe)",
    )
    parser.add_argument(
        "--trace",
        action="store_true",
        help="Print detailed status updates for the current file and API work",
    )

    args = parser.parse_args()
    if args.dedupe_apply:
        args.dedupe = True
    reporter: StatusReporter = None
    if args.trace:
        def _report(message: str) -> None:
            print(f"STATUS: {message}", flush=True)

        reporter = _report
    root = Path.cwd()
    script_dir = Path(__file__).resolve().parent
    run_started = time.time()
    print(f"Run started clock={format_clock(run_started)} root={root}")
    if is_within(script_dir, root):
        print(f"Skipping script project directory: {script_dir}")

    if not args.organize_only:
        if not os.getenv("OPENAI_API_KEY"):
            raise SystemExit("OPENAI_API_KEY is not set. Export it and try again.")

        check_dependencies()
        client = OpenAI()

        count = 0
        scanned = 0
        skipped = 0
        total = sum(1 for _ in iter_files(root, args.recursive))
        emit_status(
            reporter,
            f"Starting rename scan in {root} with {total} supported files at {format_clock()}",
        )
        started = time.time()
        for path in iter_files(root, args.recursive):
            if is_within(path, script_dir):
                skipped += 1
                continue
            scanned += 1
            stem = path.stem
            kind = get_file_kind(path)
            try:
                size_text = format_bytes(path.stat().st_size)
            except OSError:
                size_text = "unknown size"
            emit_status(reporter, f"[{scanned}/{total}] inspecting {path.name} ({kind}, {size_text})")
            if not args.no_prefix_existing:
                if parse_category_from_stem(stem):
                    emit_status(reporter, f"Skipping {path.name}: already has a FaFO category prefix")
                    skipped += 1
                    continue
                if "could_not_classify" in stem.lower():
                    emit_status(reporter, f"Skipping {path.name}: already marked could_not_classify")
                    skipped += 1
                    continue
            elif not args.mnemonically_boosted:
                if is_human_readable(stem):
                    emit_status(reporter, f"Skipping {path.name}: filename already looks human-readable")
                    skipped += 1
                    continue
                if not is_autogenerated(stem):
                    emit_status(reporter, f"Skipping {path.name}: filename is not autogenerated")
                    skipped += 1
                    continue
            else:
                if is_human_readable(stem) and not is_mnemonically_poor(stem):
                    emit_status(reporter, f"Skipping {path.name}: filename is already mnemonic enough")
                    skipped += 1
                    continue

            result = {"category": "could_not_classify", "description": ""}

            if kind == "image":
                emit_status(reporter, f"Preparing image payload for {path.name}")
                data_url = image_to_data_url(path)
                if data_url:
                    result = classify_image(client, args.model, args.detail, data_url, reporter, path.name)
            elif kind == "document":
                if path.suffix.lower() == ".pdf":
                    emit_status(reporter, f"Preparing PDF preview and text extraction for {path.name}")
                    pdf_image = extract_pdf_first_page_image(path)
                    data_url = bytes_to_data_url(pdf_image[0], pdf_image[1]) if pdf_image else None
                    text = read_text_file(path)
                    pdf_info = classify_pdf_document(
                        client, args.model, args.detail, data_url, text, reporter, path.name
                    )

                    doc_type = pdf_info.get("doc_type", "could_not_classify")
                    brand = pdf_info.get("brand", "").strip()
                    subject = pdf_info.get("subject", "").strip()
                    doc_date = pdf_info.get("date", "").strip()
                    if not doc_date:
                        doc_date = parse_date_from_text(text)
                    date_suffix = f" - {doc_date}" if doc_date else ""

                    if doc_type == "image":
                        result = {"category": "photo", "description": (subject or "image-like PDF") + date_suffix}
                    elif doc_type in {"bill", "statement", "report"}:
                        brand_label = brand if brand else "Unknown Brand"
                        base = f"{brand_label} {doc_type}"
                        if subject:
                            base = f"{base} {subject}"
                        result = {"category": "document", "description": base + date_suffix}
                    elif doc_type == "other":
                        result = {
                            "category": "document",
                            "description": (subject or path.stem.replace("_", " ")) + date_suffix,
                        }
                    else:
                        result = {"category": "document", "description": path.stem.replace("_", " ") + date_suffix}
                else:
                    emit_status(reporter, f"Extracting text from {path.name}")
                    text = read_text_file(path)
                    if text:
                        result = classify_text_document(client, args.model, text, reporter, path.name)
                    else:
                        result = {"category": "document", "description": path.stem.replace("_", " ")}
                result["category"] = "document"
            elif kind == "media":
                frame = None
                if path.suffix.lower() in {".mp4", ".mov"}:
                    emit_status(reporter, f"Extracting preview frame from {path.name}")
                    frame = extract_video_frame(path)
                if frame and frame.exists():
                    data_url = image_to_data_url(frame)
                    if data_url:
                        result = classify_image(
                            client,
                            args.model,
                            args.detail,
                            data_url,
                            reporter,
                            f"video frame for {path.name}",
                        )
                    try:
                        shutil.rmtree(frame.parent)
                    except Exception:
                        pass
                else:
                    mime, _ = mimetypes.guess_type(path.name)
                    if mime and mime.startswith("image/"):
                        emit_status(reporter, f"Preparing media-image payload for {path.name}")
                        data_url = image_to_data_url(path)
                        if data_url:
                            result = classify_image(client, args.model, args.detail, data_url, reporter, path.name)
                if result.get("category") == "could_not_classify":
                    result = {"category": "media", "description": path.stem.replace("_", " ")}
                result["category"] = "media"
            elif kind == "3d":
                emit_status(reporter, f"Treating {path.name} as a 3D file")
                result = {"category": "3d", "description": path.stem.replace("_", " ")}
            elif kind == "application":
                result = {"category": "application", "description": path.stem.replace("_", " ")}
                result["category"] = "application"

            category = result.get("category", "could_not_classify")
            description = result.get("description", "")
            emit_status(reporter, f"Classification result for {path.name}: category={category}, description={description!r}")

            new_stem = build_new_name(stem, category, description)
            new_stem = sanitize_filename(new_stem)
            if len(new_stem) > 120:
                new_stem = new_stem[:120].rstrip()

            new_path = path.with_name(f"{new_stem}{path.suffix}")
            new_path = ensure_unique_path(new_path)
            emit_status(reporter, f"Proposed rename for {path.name}: {new_path.name}")

            if args.dry_run:
                print(f"DRY-RUN: {path.name} -> {new_path.name}")
            else:
                try:
                    path.rename(new_path)
                    print(f"RENAMED: {path.name} -> {new_path.name}")
                except PermissionError:
                    if not args.no_skip_permission_errors:
                        print(f"SKIP (permission): {path.name}")
                    else:
                        raise

            count += 1
            if args.max and count >= args.max:
                break
            if (scanned % 12) == 0:
                print_phase_progress(
                    "Rename progress",
                    scanned,
                    total,
                    started,
                    renamed=count,
                    skipped=skipped,
                )
        print_phase_progress(
            "Rename summary",
            scanned,
            total,
            started,
            renamed=count,
            skipped=skipped,
        )

    if args.organize or args.organize_only:
        emit_status(reporter, f"Starting organize pass in {root}")
        organize_total = sum(1 for _ in iter_supported_paths(root, args.recursive, include_application_dirs=True))
        organize_started = time.time()
        organize_scanned = 0
        moved = 0
        for path in iter_supported_paths(root, args.recursive, include_application_dirs=True):
            if is_within(path, script_dir):
                continue
            organize_scanned += 1
            dest = route_destination(path)
            if dest:
                emit_status(reporter, f"Moving {path.name} to {dest}")
                move_to_destination(path, dest, skip_permission_errors=not args.no_skip_permission_errors)
                moved += 1
            if (organize_scanned % 12) == 0:
                print_phase_progress(
                    "Organize progress",
                    organize_scanned,
                    organize_total,
                    organize_started,
                    moved=moved,
                )
        print_phase_progress(
            "Organize summary",
            organize_scanned,
            organize_total,
            organize_started,
            moved=moved,
        )

    if args.prune_empty_dirs:
        if not is_within(script_dir, root):
            emit_status(reporter, f"Pruning empty directories under {root}")
            prune_empty_directories(root, skip_permission_errors=not args.no_skip_permission_errors)

    if args.dedupe:
        emit_status(reporter, f"Starting dedupe scan in {root}")
        dedupe_total = sum(1 for _ in iter_files(root, args.recursive) if not is_within(_, script_dir))
        dedupe_started = time.time()
        scanned, duplicates, deleted, permission_skips = dedupe_files(
            root,
            args.recursive,
            skip_permission_errors=not args.no_skip_permission_errors,
            apply=args.dedupe_apply,
            skip_dir=script_dir,
            total=dedupe_total,
            started=dedupe_started,
        )
        print_phase_progress(
            "Dedupe summary",
            scanned,
            dedupe_total,
            dedupe_started,
            mode="applied" if args.dedupe_apply else "dry-run",
            duplicates=duplicates,
            deleted=deleted,
            permission_skips=permission_skips,
        )


if __name__ == "__main__":
    main()
