#!/usr/bin/env python3
"""
Rename auto-generated filenames for images, documents, media, and application files
using OpenAI.
"""

import argparse
import time
import base64
import json
import mimetypes
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional, Tuple
import hashlib
import csv

try:
    from openai import OpenAI
except ImportError:
    import openai

    OpenAI = openai.OpenAI

MISSING_PYMUPDF_WARNED = False


def check_dependencies() -> None:
    if not shutil.which("ffmpeg"):
        raise SystemExit("ffmpeg is not installed. Install it with: brew install ffmpeg")

    try:
        import fitz  # PyMuPDF
    except Exception:
        raise SystemExit(
            "PyMuPDF is not installed. Install it with: "
            "pip install -r \"files and folders organizer - requirements.txt\""
        )


IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
DOCUMENT_EXTS = {
    ".pdf",
    ".docx",
    ".txt",
    ".rtf",
    ".csv",
    ".pptx",
    ".scad",
    ".ttf",
    ".py",
    ".html",
    ".eml",
    ".xls",
    ".psd",
    ".eps",
    ".dn",
}
MEDIA_EXTS = {
    ".mp4",
    ".mov",
    ".mp3",
    ".wav",
    ".m4a",
    ".aup3",
    ".stl",
    ".svg",
    ".ico",
    ".icl",
    ".ics",
    ".gcode",
    ".eps",
}
APPLICATION_EXTS = {".app", ".dmg", ".pkg", ".exe", ".zip", ".webp", ".xml", ".iso"}

SUPPORTED_EXTS = IMAGE_EXTS | DOCUMENT_EXTS | MEDIA_EXTS | APPLICATION_EXTS

AUTOGEN_PATTERNS = [
    r"^img_\d+$",
    r"^img\d+$",
    r"^dsc_?\d+$",
    r"^dscn\d+$",
    r"^pxl_\d+$",
    r"^vid_\d+$",
    r"^img-\d+$",
    r"^\d{8}_\d{6}$",
    r"^screenshot( |-|_)\d{4}[-_]\d{2}[-_]\d{2}.*$",
    r"^screen shot \d{4}-\d{2}-\d{2} at .*",
    r"^whatsapp image \d{4}-\d{2}-\d{2} at .*",
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    r"^[0-9a-f]{12,}$",
]

CATEGORY_TEMPLATES = {
    "document": "document - {desc}",
    "screenshot": "screenshot of {desc}",
    "photo": "photo of reality - {desc}",
    "schematic": "schematic of {desc}",
    "cartoon": "cartoon of {desc}",
    "media": "media video file {desc}",
    "application": "application file {desc}",
}

CATEGORY_PREFIXES = {
    "document": "document - ",
    "screenshot": "screenshot of ",
    "photo": "photo of reality - ",
    "schematic": "schematic of ",
    "cartoon": "cartoon of ",
    "media": "media video file ",
    "application": "application file ",
}

DEFAULT_DESTS = {
    "document": Path.home() / "Documents",
    "screenshot": Path.home() / "Pictures" / "Screenshots",
    "photo": Path.home() / "Pictures" / "Photos",
    "schematic": Path.home() / "Pictures" / "Schematics",
    "cartoon": Path.home() / "Pictures" / "Cartoons",
    "media": Path.home() / "Movies",
    "application": Path.home() / "Applications",
}

BRANDS_FILE = Path(__file__).resolve().parent / "brands.txt"
BRAND_OVERRIDES_FILE = Path(__file__).resolve().parent / "brand_overrides.csv"


def is_autogenerated(stem: str) -> bool:
    s = stem.strip().lower()
    if not s:
        return True
    for pat in AUTOGEN_PATTERNS:
        if re.fullmatch(pat, s):
            return True

    # Mostly digits/symbols, no spaces, short-ish
    if " " not in s:
        digits = sum(ch.isdigit() for ch in s)
        letters = sum(ch.isalpha() for ch in s)
        if digits >= max(6, int(0.6 * len(s))) and letters <= 2:
            return True

    # Long hex-looking strings
    if re.fullmatch(r"[0-9a-f]{16,}", s):
        return True

    return False


def is_human_readable(stem: str) -> bool:
    s = stem.strip()
    if not s:
        return False
    if is_autogenerated(s):
        return False

    tokens = [t for t in re.split(r"[ _\-]+", s) if t]
    word_tokens = [t for t in tokens if re.search(r"[A-Za-z]", t)]
    if len(word_tokens) >= 2:
        return True

    # Any alphabetic with spaces or longer length
    if re.search(r"[A-Za-z]", s) and (" " in s or len(s) >= 14):
        return True

    return False


def is_mnemonically_poor(stem: str) -> bool:
    s = stem.strip()
    if not s:
        return True
    if "could_not_classify" in s.lower():
        return False
    lower = s.lower()
    if re.search(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", lower):
        return True
    digits = sum(ch.isdigit() for ch in s)
    letters = sum(ch.isalpha() for ch in s)
    seps = sum(ch in "-_." for ch in s)
    if len(s) >= 32 and " " not in s:
        return True
    if digits >= max(6, int(0.4 * len(s))) and letters <= int(0.4 * len(s)):
        return True
    if seps >= 4 and digits >= 6:
        return True
    return False


def sanitize_filename(name: str) -> str:
    # Replace characters that are risky across filesystems
    cleaned = re.sub(r"[\\/:*?\"<>|]", "-", name)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def ensure_unique_path(path: Path) -> Path:
    if not path.exists():
        return path
    base = path.stem
    ext = path.suffix
    parent = path.parent
    i = 2
    while True:
        candidate = parent / f"{base} - {i}{ext}"
        if not candidate.exists():
            return candidate
        i += 1


def extract_date_from_stem(stem: str) -> str:
    s = stem.lower()
    # Match YYYY-MM-DD or YYYY_MM_DD
    m = re.search(r"(20\d{2})[-_](\d{2})[-_](\d{2})", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"

    # Match YYYYMMDD
    m = re.search(r"(20\d{2})(\d{2})(\d{2})", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"

    return ""


def parse_date_from_text(text: str) -> str:
    if not text:
        return ""
    # Prefer explicit YYYY-MM-DD or YYYY/MM/DD
    m = re.search(r"(20\d{2})[-/](\d{2})[-/](\d{2})", text)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"

    # Handle DD/MM/YYYY or MM/DD/YYYY
    m = re.search(r"(\d{1,2})[-/](\d{1,2})[-/](20\d{2})", text)
    if m:
        a = int(m.group(1))
        b = int(m.group(2))
        y = m.group(3)
        # Disambiguate: if a > 12, it's DD/MM; if b > 12, it's MM/DD; else assume MM/DD (US)
        if a > 12:
            d, mo = a, b
        elif b > 12:
            mo, d = a, b
        else:
            mo, d = a, b
        return f"{y}-{mo:02d}-{d:02d}"

    return ""


def year_month_from_date(date_str: str) -> tuple[str, str]:
    if not date_str:
        return "Unknown", "Unknown"
    m = re.match(r"(20\d{2})-(\d{2})-(\d{2})", date_str)
    if not m:
        return "Unknown", "Unknown"
    return m.group(1), m.group(2)


def progress_bar(scanned: int, total: int, width: int = 50) -> str:
    if total <= 0:
        return "[" + ("?" * width) + "]"
    idx = int((scanned / total) * (width - 1))
    idx = max(0, min(width - 1, idx))
    bar = ["-"] * width
    bar[idx] = "+"
    return "[" + "".join(bar) + "]"


def format_eta(seconds: float) -> str:
    seconds = max(0, int(seconds))
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    if h > 0:
        return f"{h:d}h{m:02d}m{s:02d}s"
    return f"{m:02d}m{s:02d}s"


def image_to_data_url(path: Path) -> Optional[str]:
    mime, _ = mimetypes.guess_type(path.name)
    if not mime:
        if path.suffix.lower() in {".jpg", ".jpeg"}:
            mime = "image/jpeg"
        elif path.suffix.lower() == ".png":
            mime = "image/png"
        elif path.suffix.lower() == ".webp":
            mime = "image/webp"
        elif path.suffix.lower() == ".gif":
            mime = "image/gif"
        else:
            return None

    data = path.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def bytes_to_data_url(data: bytes, mime: str) -> str:
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def load_brand_map() -> list[tuple[str, list[str]]]:
    if not BRANDS_FILE.exists():
        return []
    entries: list[tuple[str, list[str]]] = []
    for line in BRANDS_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|") if p.strip()]
        if not parts:
            continue
        canonical = parts[0]
        aliases = parts
        entries.append((canonical, aliases))
    return entries


def load_brand_overrides() -> dict[str, str]:
    if not BRAND_OVERRIDES_FILE.exists():
        return {}
    overrides: dict[str, str] = {}
    with BRAND_OVERRIDES_FILE.open(newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        for row in reader:
            if not row or row[0].startswith("#"):
                continue
            if len(row) >= 2:
                overrides[row[0].strip()] = row[1].strip()
    return overrides


def classify_image(client: OpenAI, model: str, detail: str, data_url: str) -> dict:
    if not data_url:
        return {"category": "could_not_classify", "description": ""}

    schema = {
        "type": "object",
        "properties": {
            "category": {
                "type": "string",
                "enum": [
                    "document",
                    "screenshot",
                "photo",
                "schematic",
                "cartoon",
                "media",
                "application",
                "could_not_classify",
            ],
        },
            "description": {"type": "string"},
        },
        "required": ["category", "description"],
        "additionalProperties": False,
    }

    prompt = (
        "Classify the image into one of the categories: document, screenshot, "
        "photo, schematic, cartoon, media, application, could_not_classify. "
        "If you choose document/screenshot/photo/schematic/cartoon, provide a short "
        "description (3-10 words) that will be used in a filename. "
        "If you choose media, describe what the media is (3-10 words). "
        "If you choose application, describe the app or installer (3-10 words). "
        "If the image is a document and you can recognize the type, use that (e.g., bank statement). "
        "If you choose could_not_classify, set description to an empty string."
    )

    try:
        response = client.responses.create(
            model=model,
            input=[
                {
                    "role": "user",
                    "content": [
                        {"type": "input_text", "text": prompt},
                        {"type": "input_image", "image_url": data_url, "detail": detail},
                    ],
                }
            ],
            text={
                "format": {
                    "type": "json_schema",
                    "name": "image_label",
                    "schema": schema,
                    "strict": True,
                }
            },
        )
    except Exception as exc:
        # If the file isn't a valid image (corrupt or mislabeled), skip gracefully.
        if "invalid image" in str(exc).lower() or "invalid_request_error" in str(exc).lower():
            return {"category": "could_not_classify", "description": ""}
        raise

    raw = response.output_text
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"category": "could_not_classify", "description": ""}


def classify_text_document(client: OpenAI, model: str, text: str) -> dict:
    schema = {
        "type": "object",
        "properties": {
            "category": {"type": "string", "enum": ["document", "could_not_classify"]},
            "description": {"type": "string"},
        },
        "required": ["category", "description"],
        "additionalProperties": False,
    }

    prompt = (
        "You will be given extracted text from a document. "
        "Classify it as document or could_not_classify. "
        "If document, provide a short description (3-10 words) for a filename. "
        "If could_not_classify, set description to an empty string."
    )

    response = client.responses.create(
        model=model,
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_text", "text": prompt},
                    {"type": "input_text", "text": text},
                ],
            }
        ],
        text={
            "format": {
                "type": "json_schema",
                "name": "doc_label",
                "schema": schema,
                "strict": True,
            }
        },
    )

    raw = response.output_text
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"category": "could_not_classify", "description": ""}


def classify_pdf_document(client: OpenAI, model: str, detail: str, data_url: Optional[str], text: str) -> dict:
    schema = {
        "type": "object",
        "properties": {
            "doc_type": {
                "type": "string",
                "enum": ["bill", "statement", "report", "image", "other", "could_not_classify"],
            },
            "brand": {"type": "string"},
            "subject": {"type": "string"},
            "date": {"type": "string"},
        },
        "required": ["doc_type", "brand", "subject", "date"],
        "additionalProperties": False,
    }

    prompt = (
        "Classify this PDF. Use doc_type: bill, statement, report, image, other, or could_not_classify. "
        "If a recognizable brand/logo is present, set brand to its name (e.g., TELUS, BC Hydro, RBC). "
        "Provide a short subject (3-10 words) that would be useful in a filename. "
        "Extract the most relevant document date and format it as YYYY-MM-DD (empty string if unknown). "
        "If not sure, set brand to empty string. If could_not_classify, subject can be empty."
    )

    content = [{"type": "input_text", "text": prompt}]
    if text:
        content.append({"type": "input_text", "text": text[:6000]})
    if data_url:
        content.append({"type": "input_image", "image_url": data_url, "detail": detail})

    response = client.responses.create(
        model=model,
        input=[{"role": "user", "content": content}],
        text={
            "format": {
                "type": "json_schema",
                "name": "pdf_label",
                "schema": schema,
                "strict": True,
            }
        },
    )

    raw = response.output_text
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"doc_type": "could_not_classify", "brand": "", "subject": "", "date": ""}


def extract_pdf_first_page_image(path: Path) -> Optional[Tuple[bytes, str]]:
    global MISSING_PYMUPDF_WARNED
    try:
        import fitz  # PyMuPDF
    except Exception:
        if not MISSING_PYMUPDF_WARNED:
            print("Warning: PyMuPDF not installed. PDF OCR will be skipped.", file=sys.stderr)
            MISSING_PYMUPDF_WARNED = True
        return None

    try:
        doc = fitz.open(path)
        if doc.page_count < 1:
            return None
        page = doc.load_page(0)
        pix = page.get_pixmap()
        data = pix.tobytes("png")
        return data, "image/png"
    except Exception:
        return None
    finally:
        try:
            doc.close()
        except Exception:
            pass


def extract_video_frame(path: Path) -> Optional[Path]:
    if not shutil.which("ffmpeg"):
        return None
    tmp_dir = Path(tempfile.mkdtemp(prefix="rename_media_"))
    frame_path = tmp_dir / "frame.jpg"
    cmd = [
        "ffmpeg",
        "-y",
        "-ss",
        "0",
        "-i",
        str(path),
        "-frames:v",
        "1",
        "-q:v",
        "2",
        str(frame_path),
    ]
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        return None
    if frame_path.exists():
        return frame_path
    return None


def read_text_file(path: Path, max_chars: int = 8000) -> str:
    try:
        return path.read_text(errors="ignore")[:max_chars]
    except Exception:
        return ""


def parse_category_from_stem(stem: str) -> Optional[str]:
    s = stem.lower()
    for category, prefix in CATEGORY_PREFIXES.items():
        if s.startswith(prefix):
            return category
    return None


def route_destination(path: Path) -> Optional[Path]:
    if path.name in {
        "files and folders organizer.py",
        "files and folders organizer - .env",
        "files and folders organizer - requirements.txt",
        "files and folders organizer - setup.sh",
    }:
        return None
    name = path.stem
    lower_name = name.lower()
    ext = path.suffix.lower()

    if ext == ".gcode":
        if lower_name.startswith("um2"):
            return Path.home() / "Documents" / "3D" / "Ultimaker2"
        if lower_name.startswith("ce3e3v2"):
            return Path.home() / "Documents" / "3D" / "Creality Ender 3v2"

    if ext == ".mp3":
        return Path.home() / "Music" / "playable" / "mp3"

    if ext == ".aup3":
        return Path.home() / "Music" / "Audacity Projects"

    if ext == ".psd":
        return Path.home() / "Pictures" / "Photoshop Projects"

    if ext == ".py":
        return Path.home() / "Documents" / "code" / "python"

    if ext == ".pdf":
        brand_map = load_brand_map()
        overrides = load_brand_overrides()
        lower_name = path.stem.lower()
        date_tag = extract_date_from_stem(path.stem)
        year, month = year_month_from_date(date_tag)

        # Manual override by filename
        override_brand = overrides.get(path.name)
        if override_brand:
            if "statement" in lower_name:
                return Path.home() / "Documents" / "Statements" / override_brand / year / month
            if "bill" in lower_name:
                return Path.home() / "Documents" / "Bills" / override_brand / year / month

        for brand, aliases in brand_map:
            if any(alias.lower() in lower_name for alias in aliases):
                if "statement" in lower_name:
                    return Path.home() / "Documents" / "Statements" / brand / year / month
                if "bill" in lower_name:
                    return Path.home() / "Documents" / "Bills" / brand / year / month

        if "unknown brand" in lower_name:
            if "statement" in lower_name:
                return Path.home() / "Documents" / "Statements" / "Unknown Brand" / year / month
            if "bill" in lower_name:
                return Path.home() / "Documents" / "Bills" / "Unknown Brand" / year / month

        if "report" in lower_name:
            # Keep reports in place if already readable
            if is_human_readable(path.stem):
                return None
            return Path.home() / "Documents" / "Reports"

        if "image-like" in lower_name or "image like" in lower_name:
            return Path.home() / "Pictures"

    category = parse_category_from_stem(path.stem)
    if not category:
        if ext in {".png", ".jpg", ".jpeg"}:
            return Path.home() / "Pictures"
        return None

    name = lower_name
    if category == "document":
        if "telus" in name:
            return Path.home() / "Documents" / "Bills" / "Telus"
        if "bank" in name:
            return Path.home() / "Documents" / "Banks"
        if "unknown brand" in name:
            if "statement" in name:
                return Path.home() / "Documents" / "Statements" / "Unknown Brand"
            if "bill" in name:
                return Path.home() / "Documents" / "Bills" / "Unknown Brand"

    return DEFAULT_DESTS.get(category)


def move_to_destination(path: Path, dest_dir: Path, skip_permission_errors: bool) -> None:
    if path.parent == dest_dir:
        return
    dest_dir.mkdir(parents=True, exist_ok=True)
    target = dest_dir / path.name
    target = ensure_unique_path(target)
    try:
        path.rename(target)
        print(f"MOVED: {path.name} -> {target}")
    except PermissionError:
        if skip_permission_errors:
            print(f"SKIP (permission): {path.name}")
        else:
            raise


def prune_empty_directories(root: Path, skip_permission_errors: bool) -> None:
    # Walk bottom-up to safely remove empty folders.
    dirs = [p for p in root.rglob("*") if p.is_dir()]
    for d in sorted(dirs, key=lambda p: len(p.parts), reverse=True):
        try:
            if not any(d.iterdir()):
                d.rmdir()
                print(f"REMOVED EMPTY DIR: {d}")
        except PermissionError:
            if skip_permission_errors:
                print(f"SKIP (permission): {d}")
            else:
                raise


def is_within(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except Exception:
        return False


def file_hash(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def dedupe_files(root: Path, recursive: bool, skip_permission_errors: bool, apply: bool, skip_dir: Path) -> None:
    seen: dict[str, Path] = {}
    for path in iter_files(root, recursive):
        if is_within(path, skip_dir):
            continue
        try:
            digest = file_hash(path)
        except PermissionError:
            if skip_permission_errors:
                print(f"SKIP (permission): {path}")
                continue
            raise

        if digest in seen:
            if apply:
                try:
                    path.unlink()
                    print(f"DELETED DUPLICATE: {path} (kept {seen[digest]})")
                except PermissionError:
                    if skip_permission_errors:
                        print(f"SKIP (permission): {path}")
                    else:
                        raise
            else:
                print(f"DRY-RUN DUPLICATE: {path} (would delete; kept {seen[digest]})")
        else:
            seen[digest] = path


def build_new_name(stem: str, category: str, description: str) -> str:
    date_tag = extract_date_from_stem(stem)
    date_suffix = f" - {date_tag}" if date_tag else ""

    if category == "could_not_classify" or not description.strip():
        return f"{stem} - could_not_classify{date_suffix}"

    desc = sanitize_filename(description)
    template = CATEGORY_TEMPLATES.get(category)
    if not template:
        return f"{stem} - could_not_classify{date_suffix}"

    return template.format(desc=desc) + date_suffix


def iter_files(root: Path, recursive: bool):
    if recursive:
        skip_dir_names = {".git", ".venv", "node_modules"}
        skip_suffixes = {".app", ".bundle", ".framework", ".pkg"}
        for dirpath, dirnames, filenames in os.walk(root, topdown=True, onerror=lambda _: None):
            # Prune directories we don't want to descend into
            pruned = []
            for d in dirnames:
                lower = d.lower()
                if lower in skip_dir_names or any(lower.endswith(s) for s in skip_suffixes):
                    continue
                pruned.append(d)
            dirnames[:] = pruned

            for filename in filenames:
                path = Path(dirpath) / filename
                if path.suffix.lower() in SUPPORTED_EXTS:
                    yield path
    else:
        for path in root.iterdir():
            if path.is_file() and path.suffix.lower() in SUPPORTED_EXTS:
                yield path


def get_file_kind(path: Path) -> str:
    ext = path.suffix.lower()
    if ext in IMAGE_EXTS:
        return "image"
    if ext in DOCUMENT_EXTS:
        return "document"
    if ext in MEDIA_EXTS:
        return "media"
    if ext in APPLICATION_EXTS:
        return "application"
    return "other"


def main():
    parser = argparse.ArgumentParser(
        description="Rename auto-generated filenames for images, documents, media, and application files."
    )
    parser.add_argument("-r", "--recursive", action="store_true", help="Recurse into subdirectories")
    parser.add_argument("--dry-run", action="store_true", help="Print actions without renaming")
    parser.add_argument("--model", default="gpt-4.1-mini", help="OpenAI model to use")
    parser.add_argument("--detail", default="high", choices=["low", "high", "auto"], help="Image detail level")
    parser.add_argument("--max", type=int, default=0, help="Max images to process (0 = no limit)")
    parser.add_argument(
        "--no-skip-permission-errors",
        action="store_true",
        help="Fail on permission errors instead of skipping",
    )
    parser.add_argument(
        "--mnemonically-boosted",
        action="store_true",
        help="Rename files with low-mnemonic filenames (e.g., UUIDs, long tokenized names)",
    )
    parser.add_argument(
        "--no-prefix-existing",
        action="store_true",
        help="Disable default behavior of prefixing supported files lacking category prefixes",
    )
    parser.add_argument(
        "--organize",
        action="store_true",
        help="Move files with recognized naming patterns into destination folders",
    )
    parser.add_argument(
        "--organize-only",
        action="store_true",
        help="Only organize files; do not rename",
    )
    parser.add_argument(
        "--prune-empty-dirs",
        action="store_true",
        help="Remove empty directories under the root (requires -r to be useful)",
    )
    parser.add_argument(
        "--dedupe",
        action="store_true",
        help="Find duplicate files by content hash (dry-run by default)",
    )
    parser.add_argument(
        "--dedupe-apply",
        action="store_true",
        help="Actually delete duplicates when used with --dedupe",
    )

    args = parser.parse_args()
    root = Path.cwd()
    script_dir = Path(__file__).resolve().parent
    if is_within(script_dir, root):
        print(f"Skipping script project directory: {script_dir}")

    if not args.organize_only:
        if not os.getenv("OPENAI_API_KEY"):
            raise SystemExit("OPENAI_API_KEY is not set. Export it and try again.")

        check_dependencies()
        client = OpenAI()

        count = 0
        scanned = 0
        skipped = 0
        total = sum(1 for _ in iter_files(root, args.recursive))
        started = time.time()
        for path in iter_files(root, args.recursive):
            if is_within(path, script_dir):
                skipped += 1
                continue
            scanned += 1
            stem = path.stem
            if not args.no_prefix_existing:
                if parse_category_from_stem(stem):
                    skipped += 1
                    continue
                if "could_not_classify" in stem.lower():
                    skipped += 1
                    continue
            elif not args.mnemonically_boosted:
                if is_human_readable(stem):
                    skipped += 1
                    continue
                if not is_autogenerated(stem):
                    skipped += 1
                    continue
            else:
                if is_human_readable(stem) and not is_mnemonically_poor(stem):
                    skipped += 1
                    continue

            kind = get_file_kind(path)
            result = {"category": "could_not_classify", "description": ""}

            if kind == "image":
                data_url = image_to_data_url(path)
                if data_url:
                    result = classify_image(client, args.model, args.detail, data_url)
            elif kind == "document":
                if path.suffix.lower() == ".pdf":
                    pdf_image = extract_pdf_first_page_image(path)
                    data_url = bytes_to_data_url(pdf_image[0], pdf_image[1]) if pdf_image else None
                    text = read_text_file(path)
                    pdf_info = classify_pdf_document(client, args.model, args.detail, data_url, text)

                    doc_type = pdf_info.get("doc_type", "could_not_classify")
                    brand = pdf_info.get("brand", "").strip()
                    subject = pdf_info.get("subject", "").strip()
                    doc_date = pdf_info.get("date", "").strip()
                    if not doc_date:
                        doc_date = parse_date_from_text(text)
                    date_suffix = f" - {doc_date}" if doc_date else ""

                    if doc_type == "image":
                        result = {"category": "photo", "description": (subject or "image-like PDF") + date_suffix}
                    elif doc_type in {"bill", "statement", "report"}:
                        brand_label = brand if brand else "Unknown Brand"
                        base = f"{brand_label} {doc_type}"
                        if subject:
                            base = f"{base} {subject}"
                        result = {"category": "document", "description": base + date_suffix}
                    elif doc_type == "other":
                        result = {
                            "category": "document",
                            "description": (subject or path.stem.replace("_", " ")) + date_suffix,
                        }
                    else:
                        result = {"category": "document", "description": path.stem.replace("_", " ") + date_suffix}
                else:
                    text = read_text_file(path)
                    if text:
                        result = classify_text_document(client, args.model, text)
                    else:
                        result = {"category": "document", "description": path.stem.replace("_", " ")}
                result["category"] = "document"
            elif kind == "media":
                frame = None
                if path.suffix.lower() in {".mp4", ".mov"}:
                    frame = extract_video_frame(path)
                if frame and frame.exists():
                    data_url = image_to_data_url(frame)
                    if data_url:
                        result = classify_image(client, args.model, args.detail, data_url)
                    try:
                        shutil.rmtree(frame.parent)
                    except Exception:
                        pass
                else:
                    mime, _ = mimetypes.guess_type(path.name)
                    if mime and mime.startswith("image/"):
                        data_url = image_to_data_url(path)
                        if data_url:
                            result = classify_image(client, args.model, args.detail, data_url)
                if result.get("category") == "could_not_classify":
                    result = {"category": "media", "description": path.stem.replace("_", " ")}
                result["category"] = "media"
            elif kind == "application":
                result = {"category": "application", "description": path.stem.replace("_", " ")}
                result["category"] = "application"

            category = result.get("category", "could_not_classify")
            description = result.get("description", "")

            new_stem = build_new_name(stem, category, description)
            new_stem = sanitize_filename(new_stem)
            if len(new_stem) > 120:
                new_stem = new_stem[:120].rstrip()

            new_path = path.with_name(f"{new_stem}{path.suffix}")
            new_path = ensure_unique_path(new_path)

            if args.dry_run:
                print(f"DRY-RUN: {path.name} -> {new_path.name}")
            else:
                try:
                    path.rename(new_path)
                    print(f"RENAMED: {path.name} -> {new_path.name}")
                except PermissionError:
                    if not args.no_skip_permission_errors:
                        print(f"SKIP (permission): {path.name}")
                    else:
                        raise

            count += 1
            if args.max and count >= args.max:
                break
            if (scanned % 12) == 0:
                elapsed = max(1.0, time.time() - started)
                rate = scanned / elapsed
                remaining = max(0, total - scanned)
                bar = progress_bar(scanned, total)
                eta = format_eta(remaining / rate) if rate > 0 else "??m??s"
                print(
                    f"\n\nProgress {bar} scanned={scanned} renamed={count} skipped={skipped} "
                    f"remaining={remaining} rate={rate:.2f} files/sec eta={eta}\n\n"
                )
        elapsed = max(1.0, time.time() - started)
        rate = scanned / elapsed
        remaining = max(0, total - scanned)
        bar = progress_bar(scanned, total)
        eta = format_eta(remaining / rate) if rate > 0 else "??m??s"
        print(
            f"\n\nRename summary {bar} scanned={scanned} renamed={count} skipped={skipped} "
            f"remaining={remaining} rate={rate:.2f} files/sec eta={eta}\n\n"
        )

    if args.organize or args.organize_only:
        for path in iter_files(root, args.recursive):
            if is_within(path, script_dir):
                continue
            dest = route_destination(path)
            if dest:
                move_to_destination(path, dest, skip_permission_errors=not args.no_skip_permission_errors)

    if args.prune_empty_dirs:
        if not is_within(script_dir, root):
            prune_empty_directories(root, skip_permission_errors=not args.no_skip_permission_errors)

    if args.dedupe:
        dedupe_files(
            root,
            args.recursive,
            skip_permission_errors=not args.no_skip_permission_errors,
            apply=args.dedupe_apply,
            skip_dir=script_dir,
        )


if __name__ == "__main__":
    main()
