#!/usr/bin/env python3
"""
Rename auto-generated filenames for images, documents, media, and application files
using OpenAI.
"""

import argparse
import base64
import json
import mimetypes
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional, Tuple

from openai import OpenAI

MISSING_PYMUPDF_WARNED = False


def check_dependencies() -> None:
    if not shutil.which("ffmpeg"):
        raise SystemExit("ffmpeg is not installed. Install it with: brew install ffmpeg")

    try:
        import fitz  # PyMuPDF
    except Exception:
        raise SystemExit("PyMuPDF is not installed. Install it with: pip install pymupdf")


IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
DOCUMENT_EXTS = {
    ".pdf",
    ".docx",
    ".txt",
    ".rtf",
    ".csv",
    ".pptx",
    ".scad",
    ".ttf",
    ".py",
    ".html",
    ".eml",
    ".xls",
    ".psd",
    ".eps",
    ".dn",
}
MEDIA_EXTS = {
    ".mp4",
    ".mov",
    ".mp3",
    ".wav",
    ".m4a",
    ".stl",
    ".svg",
    ".ico",
    ".icl",
    ".ics",
    ".gcode",
    ".eps",
}
APPLICATION_EXTS = {".app", ".dmg", ".pkg", ".exe", ".zip", ".webp", ".xml", ".iso"}

SUPPORTED_EXTS = IMAGE_EXTS | DOCUMENT_EXTS | MEDIA_EXTS | APPLICATION_EXTS

AUTOGEN_PATTERNS = [
    r"^img_\d+$",
    r"^img\d+$",
    r"^dsc_?\d+$",
    r"^dscn\d+$",
    r"^pxl_\d+$",
    r"^vid_\d+$",
    r"^img-\d+$",
    r"^\d{8}_\d{6}$",
    r"^screenshot( |-|_)\d{4}[-_]\d{2}[-_]\d{2}.*$",
    r"^screen shot \d{4}-\d{2}-\d{2} at .*",
    r"^whatsapp image \d{4}-\d{2}-\d{2} at .*",
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    r"^[0-9a-f]{12,}$",
]

CATEGORY_TEMPLATES = {
    "document": "document - {desc}",
    "screenshot": "screenshot of {desc}",
    "photo": "photo of reality - {desc}",
    "schematic": "schematic of {desc}",
    "cartoon": "cartoon of {desc}",
    "media": "media video file {desc}",
    "application": "application file {desc}",
}


def is_autogenerated(stem: str) -> bool:
    s = stem.strip().lower()
    if not s:
        return True
    for pat in AUTOGEN_PATTERNS:
        if re.fullmatch(pat, s):
            return True

    # Mostly digits/symbols, no spaces, short-ish
    if " " not in s:
        digits = sum(ch.isdigit() for ch in s)
        letters = sum(ch.isalpha() for ch in s)
        if digits >= max(6, int(0.6 * len(s))) and letters <= 2:
            return True

    # Long hex-looking strings
    if re.fullmatch(r"[0-9a-f]{16,}", s):
        return True

    return False


def is_human_readable(stem: str) -> bool:
    s = stem.strip()
    if not s:
        return False
    if is_autogenerated(s):
        return False

    tokens = [t for t in re.split(r"[ _\-]+", s) if t]
    word_tokens = [t for t in tokens if re.search(r"[A-Za-z]", t)]
    if len(word_tokens) >= 2:
        return True

    # Any alphabetic with spaces or longer length
    if re.search(r"[A-Za-z]", s) and (" " in s or len(s) >= 14):
        return True

    return False


def sanitize_filename(name: str) -> str:
    # Replace characters that are risky across filesystems
    cleaned = re.sub(r"[\\/:*?\"<>|]", "-", name)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def ensure_unique_path(path: Path) -> Path:
    if not path.exists():
        return path
    base = path.stem
    ext = path.suffix
    parent = path.parent
    i = 2
    while True:
        candidate = parent / f"{base} - {i}{ext}"
        if not candidate.exists():
            return candidate
        i += 1


def extract_date_from_stem(stem: str) -> str:
    s = stem.lower()
    # Match YYYY-MM-DD or YYYY_MM_DD
    m = re.search(r"(20\d{2})[-_](\d{2})[-_](\d{2})", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"

    # Match YYYYMMDD
    m = re.search(r"(20\d{2})(\d{2})(\d{2})", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"

    return ""


def image_to_data_url(path: Path) -> Optional[str]:
    mime, _ = mimetypes.guess_type(path.name)
    if not mime:
        if path.suffix.lower() in {".jpg", ".jpeg"}:
            mime = "image/jpeg"
        elif path.suffix.lower() == ".png":
            mime = "image/png"
        elif path.suffix.lower() == ".webp":
            mime = "image/webp"
        elif path.suffix.lower() == ".gif":
            mime = "image/gif"
        else:
            return None

    data = path.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def bytes_to_data_url(data: bytes, mime: str) -> str:
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def classify_image(client: OpenAI, model: str, detail: str, data_url: str) -> dict:
    if not data_url:
        return {"category": "could_not_classify", "description": ""}

    schema = {
        "type": "object",
        "properties": {
            "category": {
                "type": "string",
                "enum": [
                    "document",
                    "screenshot",
                "photo",
                "schematic",
                "cartoon",
                "media",
                "application",
                "could_not_classify",
            ],
        },
            "description": {"type": "string"},
        },
        "required": ["category", "description"],
        "additionalProperties": False,
    }

    prompt = (
        "Classify the image into one of the categories: document, screenshot, "
        "photo, schematic, cartoon, media, application, could_not_classify. "
        "If you choose document/screenshot/photo/schematic/cartoon, provide a short "
        "description (3-10 words) that will be used in a filename. "
        "If you choose media, describe what the media is (3-10 words). "
        "If you choose application, describe the app or installer (3-10 words). "
        "If the image is a document and you can recognize the type, use that (e.g., bank statement). "
        "If you choose could_not_classify, set description to an empty string."
    )

    response = client.responses.create(
        model=model,
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_text", "text": prompt},
                    {"type": "input_image", "image_url": data_url, "detail": detail},
                ],
            }
        ],
        text={
            "format": {
                "type": "json_schema",
                "name": "image_label",
                "schema": schema,
                "strict": True,
            }
        },
    )

    raw = response.output_text
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"category": "could_not_classify", "description": ""}


def classify_text_document(client: OpenAI, model: str, text: str) -> dict:
    schema = {
        "type": "object",
        "properties": {
            "category": {"type": "string", "enum": ["document", "could_not_classify"]},
            "description": {"type": "string"},
        },
        "required": ["category", "description"],
        "additionalProperties": False,
    }

    prompt = (
        "You will be given extracted text from a document. "
        "Classify it as document or could_not_classify. "
        "If document, provide a short description (3-10 words) for a filename. "
        "If could_not_classify, set description to an empty string."
    )

    response = client.responses.create(
        model=model,
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_text", "text": prompt},
                    {"type": "input_text", "text": text},
                ],
            }
        ],
        text={
            "format": {
                "type": "json_schema",
                "name": "doc_label",
                "schema": schema,
                "strict": True,
            }
        },
    )

    raw = response.output_text
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"category": "could_not_classify", "description": ""}


def extract_pdf_first_page_image(path: Path) -> Optional[Tuple[bytes, str]]:
    global MISSING_PYMUPDF_WARNED
    try:
        import fitz  # PyMuPDF
    except Exception:
        if not MISSING_PYMUPDF_WARNED:
            print("Warning: PyMuPDF not installed. PDF OCR will be skipped.", file=sys.stderr)
            MISSING_PYMUPDF_WARNED = True
        return None

    try:
        doc = fitz.open(path)
        if doc.page_count < 1:
            return None
        page = doc.load_page(0)
        pix = page.get_pixmap()
        data = pix.tobytes("png")
        return data, "image/png"
    except Exception:
        return None
    finally:
        try:
            doc.close()
        except Exception:
            pass


def extract_video_frame(path: Path) -> Optional[Path]:
    if not shutil.which("ffmpeg"):
        return None
    tmp_dir = Path(tempfile.mkdtemp(prefix="rename_media_"))
    frame_path = tmp_dir / "frame.jpg"
    cmd = [
        "ffmpeg",
        "-y",
        "-ss",
        "0",
        "-i",
        str(path),
        "-frames:v",
        "1",
        "-q:v",
        "2",
        str(frame_path),
    ]
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        return None
    if frame_path.exists():
        return frame_path
    return None


def read_text_file(path: Path, max_chars: int = 8000) -> str:
    try:
        return path.read_text(errors="ignore")[:max_chars]
    except Exception:
        return ""


def build_new_name(stem: str, category: str, description: str) -> str:
    date_tag = extract_date_from_stem(stem)
    date_suffix = f" - {date_tag}" if date_tag else ""

    if category == "could_not_classify" or not description.strip():
        return f"{stem} - could_not_classify{date_suffix}"

    desc = sanitize_filename(description)
    template = CATEGORY_TEMPLATES.get(category)
    if not template:
        return f"{stem} - could_not_classify{date_suffix}"

    return template.format(desc=desc) + date_suffix


def iter_files(root: Path, recursive: bool):
    if recursive:
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in SUPPORTED_EXTS:
                yield path
    else:
        for path in root.iterdir():
            if path.is_file() and path.suffix.lower() in SUPPORTED_EXTS:
                yield path


def get_file_kind(path: Path) -> str:
    ext = path.suffix.lower()
    if ext in IMAGE_EXTS:
        return "image"
    if ext in DOCUMENT_EXTS:
        return "document"
    if ext in MEDIA_EXTS:
        return "media"
    if ext in APPLICATION_EXTS:
        return "application"
    return "other"


def main():
    parser = argparse.ArgumentParser(
        description="Rename auto-generated filenames for images, documents, media, and application files."
    )
    parser.add_argument("-r", "--recursive", action="store_true", help="Recurse into subdirectories")
    parser.add_argument("--dry-run", action="store_true", help="Print actions without renaming")
    parser.add_argument("--model", default="gpt-4.1-mini", help="OpenAI model to use")
    parser.add_argument("--detail", default="high", choices=["low", "high", "auto"], help="Image detail level")
    parser.add_argument("--max", type=int, default=0, help="Max images to process (0 = no limit)")

    args = parser.parse_args()
    root = Path.cwd()

    if not os.getenv("OPENAI_API_KEY"):
        raise SystemExit("OPENAI_API_KEY is not set. Export it and try again.")

    check_dependencies()

    client = OpenAI()

    count = 0
    for path in iter_files(root, args.recursive):
        stem = path.stem
        if is_human_readable(stem):
            continue
        if not is_autogenerated(stem):
            continue

        kind = get_file_kind(path)
        result = {"category": "could_not_classify", "description": ""}

        if kind == "image":
            data_url = image_to_data_url(path)
            if data_url:
                result = classify_image(client, args.model, args.detail, data_url)
        elif kind == "document":
            if path.suffix.lower() == ".pdf":
                pdf_image = extract_pdf_first_page_image(path)
                if pdf_image:
                    data_url = bytes_to_data_url(pdf_image[0], pdf_image[1])
                    result = classify_image(client, args.model, args.detail, data_url)
                else:
                    result = {"category": "document", "description": path.stem.replace("_", " ")}
            else:
                text = read_text_file(path)
                if text:
                    result = classify_text_document(client, args.model, text)
                else:
                    result = {"category": "document", "description": path.stem.replace("_", " ")}
            result["category"] = "document"
        elif kind == "media":
            frame = None
            if path.suffix.lower() in {".mp4", ".mov"}:
                frame = extract_video_frame(path)
            if frame and frame.exists():
                data_url = image_to_data_url(frame)
                if data_url:
                    result = classify_image(client, args.model, args.detail, data_url)
                try:
                    shutil.rmtree(frame.parent)
                except Exception:
                    pass
            else:
                mime, _ = mimetypes.guess_type(path.name)
                if mime and mime.startswith("image/"):
                    data_url = image_to_data_url(path)
                    if data_url:
                        result = classify_image(client, args.model, args.detail, data_url)
                if result.get("category") == "could_not_classify":
                    result = {"category": "media", "description": path.stem.replace("_", " ")}
            result["category"] = "media"
        elif kind == "application":
            result = {"category": "application", "description": path.stem.replace("_", " ")}
            result["category"] = "application"

        category = result.get("category", "could_not_classify")
        description = result.get("description", "")

        new_stem = build_new_name(stem, category, description)
        new_stem = sanitize_filename(new_stem)
        if len(new_stem) > 120:
            new_stem = new_stem[:120].rstrip()

        new_path = path.with_name(f"{new_stem}{path.suffix}")
        new_path = ensure_unique_path(new_path)

        if args.dry_run:
            print(f"DRY-RUN: {path.name} -> {new_path.name}")
        else:
            path.rename(new_path)
            print(f"RENAMED: {path.name} -> {new_path.name}")

        count += 1
        if args.max and count >= args.max:
            break


if __name__ == "__main__":
    main()
